version: '3.8'

services:
  php8-litespeed:
    container_name: php8-litespeed
    build:
      context: ./php8_litespeed
      args:
        - LSPHP_VERSION=${LSPHP_VERSION}
        - PHP_VERSION=${PHP_VERSION}
    ports:
      - "7080:7080"
      - "8088:8088"
    volumes:
      - ./www:/var/www
    depends_on:
      - "mysql8"

  mysql8:
    container_name: mysql8
    build:
      context: ./mysql8
    command:
      --default-authentication-plugin=mysql_native_password
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "Asia/Tokyo"

volumes:
  mysql_data:
